const SET_COMPANY_ID = 'SET_COMPANY_ID';
const SET_PROPERTY_ID = 'SET_PROPERTY_ID';
const SET_RESOURCE_ID = 'SET_RESOURCE_ID';

const LIST_RESOURCE_BEGIN = 'LIST_RESOURCE_BEGIN';
const LIST_RESOURCE_SUCCESS = 'LIST_RESOURCE_SUCCESS';
const LIST_RESOURCE_ERROR= 'LIST_RESOURCE_ERROR';
const FETCH_RESOURCE_BEGIN = 'FETCH_RESOURCE_BEGIN';
const FETCH_RESOURCE_SUCCESS = 'FETCH_RESOURCE_SUCCESS';
const FETCH_RESOURCE_ERROR= 'FETCH_RESOURCE_ERROR';
const CREATE_RESOURCE_BEGIN = 'CREATE_RESOURCE_BEGIN';
const CREATE_RESOURCE_SUCCESS = 'CREATE_RESOURCE_SUCCESS';
const CREATE_RESOURCE_ERROR = 'CREATE_RESOURCE_ERROR';
const UPDATE_RESOURCE_BEGIN = 'UPDATE_RESOURCE_BEGIN';
const UPDATE_RESOURCE_SUCCESS = 'UPDATE_RESOURCE_SUCCESS';
const UPDATE_RESOURCE_ERROR = 'UPDATE_RESOURCE_ERROR';
const REVISE_RESOURCE_BEGIN = 'REVISE_RESOURCE_BEGIN';
const REVISE_RESOURCE_SUCCESS = 'REVISE_RESOURCE_SUCCESS';
const REVISE_RESOURCE_ERROR = 'REVISE_RESOURCE_ERROR';
const DELETE_RESOURCE_BEGIN = 'DELETE_RESOURCE_BEGIN';
const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS';
const DELETE_RESOURCE_ERROR = 'DELETE_RESOURCE_ERROR';

export {
	SET_COMPANY_ID,
	SET_PROPERTY_ID,
	SET_RESOURCE_ID,
	LIST_RESOURCE_BEGIN,
	LIST_RESOURCE_SUCCESS,
	LIST_RESOURCE_ERROR,
	FETCH_RESOURCE_BEGIN,
	FETCH_RESOURCE_SUCCESS,
	FETCH_RESOURCE_ERROR,
	CREATE_RESOURCE_BEGIN,
	CREATE_RESOURCE_SUCCESS,
	CREATE_RESOURCE_ERROR,
	UPDATE_RESOURCE_BEGIN,
	UPDATE_RESOURCE_SUCCESS,
	UPDATE_RESOURCE_ERROR,
	REVISE_RESOURCE_BEGIN,
	REVISE_RESOURCE_SUCCESS,
	REVISE_RESOURCE_ERROR,
	DELETE_RESOURCE_BEGIN,
	DELETE_RESOURCE_SUCCESS,
	DELETE_RESOURCE_ERROR,
}


